[tool.poetry]
name = "advent-of-code-2024"
version = "0.1.0"
description = ""
authors = ["Cameron Spickert <cspickert@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
pytest = "^8.3.4"
ruff = "^0.8.3"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest]
testpaths = "tests"