import pytest
from day08 import parse_data, part1, part2
from io import StringIO


@pytest.fixture
def example_input():
    return StringIO(
        """\
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""
    )


def test_part1(example_input):
    data = parse_data(example_input)
    assert part1(data) == 14


def test_part2(example_input):
    data = parse_data(example_input)
    assert part2(data) == 34
